- CHANGELOG.md
- pyproject.toml
- src/opentaskpy/config/schemas.py
- test/cfg/transfers/email-transfer.json
- tests/test_schema_validate.py
Make sure protocol is always defined, regardless of the type.
> Fix protocol validation. Add missing example config

- CHANGELOG.md
- README.md
- pyproject.toml
- src/opentaskpy/config/loader.py
- src/opentaskpy/config/schemas.py
- src/opentaskpy/plugins/lookup/random.py
- src/opentaskpy/task_run.py
- tests/test_config_loader.py
Fix #17 
Allowing overrides for all sorts of things. Updated README.md to describe this functionality
Also added more docs about addons and plugins. Added a random lookup plugin as an example basic plugin
> Add code for overriding variables

- .devcontainer/devcontainer.json
- .vscode/settings.json
Remove remnants from another repo from settings and devcontainer JSON files
> Remove bad settings [skip ci]

- CHANGELOG.md
- pyproject.toml
- src/opentaskpy/config/schemas/execution/ssh/protocol.json
- src/opentaskpy/config/schemas/transfer/sftp_destination/protocol.json
- src/opentaskpy/config/schemas/transfer/sftp_source/protocol.json
- src/opentaskpy/config/schemas/transfer/ssh_destination/protocol.json
- src/opentaskpy/config/schemas/transfer/ssh_source/protocol.json
Fix issue where ports were being ignored because the schema was wrong
> Fix schema for port config

- CHANGELOG.md
- pyproject.toml
- src/opentaskpy/cli/task_run.py
- src/opentaskpy/remotehandlers/sftp.py
- src/opentaskpy/remotehandlers/ssh.py
- src/opentaskpy/taskhandlers/transfer.py
Minor update to give some log output for PCA delete
> Logging update

- CHANGELOG.md
- README.md
- pyproject.toml
- src/opentaskpy/cli/task_run.py
- src/opentaskpy/config/loader.py
- src/opentaskpy/remotehandlers/local.py
- src/opentaskpy/remotehandlers/sftp.py
- src/opentaskpy/remotehandlers/ssh.py
- src/opentaskpy/taskrun.py
- tests/test_config_loader.py
- tests/test_task_run.py
- tests/test_taskhandler_transfer_local.py
* Allow for overriding the variable file loaded at runtime. This is useful for running against multiple environments but using the same task definitions.
* Updated chmod related code and ensure that valid tests exist for it
> Add custom variable files

- CHANGELOG.md
- pyproject.toml
- src/opentaskpy/taskhandlers/transfer.py
This pull request updates the versioning format to "vYY.WW.PATCH[-TAG]" and fixes the file transfers to ensure that only files matching the regex are actually transferred. This resolves an issue where incorrect files were being transferred.
> Update versioning format and fix file transfers

- .devcontainer/devcontainer.json
- .pre-commit-config.yaml
- .vscode/settings.json
- CHANGELOG.md
- pyproject.toml
- src/opentaskpy/config/loader.py
- src/opentaskpy/config/schemas.py
- src/opentaskpy/config/schemas/transfer/sftp_destination/protocol.json
- src/opentaskpy/config/schemas/transfer/sftp_source/protocol.json
- src/opentaskpy/config/schemas/transfer/ssh_destination/protocol.json
- src/opentaskpy/config/schemas/transfer/ssh_source/protocol.json
- src/opentaskpy/exceptions.py
- src/opentaskpy/otflogging.py
- src/opentaskpy/plugins/lookup/file.py
- src/opentaskpy/plugins/lookup/http_json.py
- src/opentaskpy/plugins/lookup/random_number.py
- src/opentaskpy/remotehandlers/email.py
- src/opentaskpy/remotehandlers/local.py
- src/opentaskpy/remotehandlers/remotehandler.py
- src/opentaskpy/remotehandlers/sftp.py
- src/opentaskpy/remotehandlers/ssh.py
- src/opentaskpy/taskhandlers/batch.py
- src/opentaskpy/taskhandlers/execution.py
- src/opentaskpy/taskhandlers/taskhandler.py
- src/opentaskpy/taskrun.py
- tests/fixtures/ssh_clients.py
- tests/test_config_loader.py
- tests/test_taskhandler_transfer_sftp.py
- tests/test_taskhandler_transfer_ssh.py
This pull request adds support for passing an RSA key into SSH type handlers, allowing for more flexible authentication options. It also removes the --preview mode from the black formatter and updates the version to 24.1.1.
> Allow passing an RSA key into SSH type handlers

- CHANGELOG.md
- README.md
- pyproject.toml
- src/opentaskpy/cli/batch_validator.py
- src/opentaskpy/cli/task_run.py
- src/opentaskpy/config/loader.py
- src/opentaskpy/taskhandlers/batch.py
- src/opentaskpy/taskrun.py
- tests/test_batch_validator.py
This pull request adds a batch config validator and updates the --noop functionality to work correctly for batch operations.
> Add batch config validator and update --noop functionality

- test/cfg/executions/sleep-5.json
- tests/test_taskhandler_batch.py
Add another test to run 10x batch tasks together
Spawned from #50
> Additional batch task test

- .devcontainer/devcontainer.json
- .vscode/settings.json
- CHANGELOG.md
- pyproject.toml
- src/opentaskpy/otflogging.py
- src/opentaskpy/remotehandlers/email.py
- src/opentaskpy/remotehandlers/local.py
- src/opentaskpy/remotehandlers/sftp.py
- src/opentaskpy/remotehandlers/ssh.py
- src/opentaskpy/taskhandlers/batch.py
- src/opentaskpy/taskhandlers/execution.py
- src/opentaskpy/taskhandlers/transfer.py
* Fixes #60 
* Fixes #61 
Mainly logging related with some minor logic fixes for better readability
> Minor bug fixes

- .devcontainer/devcontainer.json
- .github/workflows/test.yml
- .pre-commit-config.yaml
- .vscode/settings.json
- CHANGELOG.md
- pyproject.toml
- src/opentaskpy/remotehandlers/local.py
- test/cfg/plugins/lookup/test_plugin.py
- tests/fixtures/ssh_clients.py
- tests/test_batch_validator.py
- tests/test_config_loader.py
- tests/test_docker_task_run.py
- tests/test_logging.py
- tests/test_plugin_file.py
- tests/test_task_run.py
- tests/test_taskhandler_batch.py
- tests/test_taskhandler_execution_local.py
- tests/test_taskhandler_execution_ssh.py
- tests/test_taskhandler_transfer_email.py
- tests/test_taskhandler_transfer_local.py
- tests/test_taskhandler_transfer_sftp.py
- tests/test_taskhandler_transfer_ssh.py
Update to linting and some formatting. No actual functionallity changes
> Update pre-commit config, VSCode settings, and linting config

- CHANGELOG.md
- pyproject.toml
- src/opentaskpy/taskhandlers/transfer.py
- tests/test_task_run.py
- tests/test_taskhandler_transfer_sftp.py
This pull request updates the encryption and decryption logic in the Transfer class. It fixes issues related to encryption and decryption and adds additional tests for SFTP transfers.
> Fix encryption and decryption when using non-local protocols

- CHANGELOG.md
- pyproject.toml
- src/opentaskpy/remotehandlers/local.py
- src/opentaskpy/taskhandlers/transfer.py
- tests/test_taskhandler_transfer_sftp.py
This pull request fixes an issue where using decryption meant that the encrypted file was also transferred to the destination. It also includes improvements to the logging.
> Fix issue with decryption and improve logging

- .github/CODEOWNERS
- .github/workflows/test.yml
- CHANGELOG.md
- README.md
- pyproject.toml
- src/opentaskpy/config/loader.py
- tests/test_config_loader.py
* Allow loading multiple variables files with `OTF_VARIABLES_FILE` env var
* Fix variable evaluation when rendering nested vars
* Update GitHub actions to latest node v20 versions
* Fix `CODEOWNERS` file
> fix: Config loader changes

- CHANGELOG.md
- src/opentaskpy/remotehandlers/sftp.py
- tests/test_taskhandler_transfer_sftp.py
Fixes #101 
Add recursive check when creating destination directories on SFTP servers.
> 101 sftp destination directory is not recursively created

- .vscode/launch.json
- CHANGELOG.md
- src/opentaskpy/config/schemas/execution/ssh/protocol.json
- src/opentaskpy/config/schemas/transfer/sftp_destination/protocol.json
- src/opentaskpy/config/schemas/transfer/sftp_source/protocol.json
- src/opentaskpy/config/schemas/transfer/ssh_destination/protocol.json
- src/opentaskpy/config/schemas/transfer/ssh_source/protocol.json
- src/opentaskpy/remotehandlers/sftp.py
- src/opentaskpy/remotehandlers/ssh.py
- src/opentaskpy/remotehandlers/ssh_utils.py
- test/cfg/transfers/sftp-basic.json
- test/cfg/variables.json.j2
- test/createTestDirectories.sh
- tests/test_remotehandler.py
- tests/test_ssh_execution_schema_validate.py
- tests/test_taskhandler_execution_ssh.py
- tests/test_taskhandler_transfer_sftp.py
- tests/test_taskhandler_transfer_ssh.py
Closes #99, https://github.com/adammcdonagh/open-task-framework/security/code-scanning/1, https://github.com/adammcdonagh/open-task-framework/security/code-scanning/2
This pull request introduces SSH host key validation for SFTP and SSH transfers, updates configuration schemas, and adds new tests. The changes ensure that SSH connections validate host keys before proceeding, enhancing security.
* Added `hostKeyValidation` and `knownHostsFile` fields to various protocol schemas (`src/opentaskpy/config/schemas/execution/ssh/protocol.json`, `src/opentaskpy/config/schemas/transfer/sftp_destination/protocol.json`, `src/opentaskpy/config/schemas/transfer/sftp_source/protocol.json`, `src/opentaskpy/config/schemas/transfer/ssh_destination/protocol.json`, …
> fix: Add way to enable host key validation for SSH/SFTP

- .github/workflows/daily_test.yml
- CHANGELOG.md
- pyproject.toml
- src/opentaskpy/taskhandlers/batch.py
- test/cfg/batch/AM-test-.json
- test/cfg/batch/AM-test.json
- test/cfg/transfers/sftp-timeout-long.json
* [`src/opentaskpy/taskhandlers/batch.py`](diffhunk://#diff-927ba53bba2885aea6fdc8f48b73bb5dd08c2c54b8b551a0c358d2864557e6b3L351-R358): Modified the logic to check for tasks that are still in `RUNNING` or `NOT_STARTED` states and added debug logging for remaining tasks. This ensures that all tasks run before exiting.
> fix: Batch logic

- CHANGELOG.md
- pyproject.toml
- src/opentaskpy/config/schemas/transfer/email_destination.json
- src/opentaskpy/remotehandlers/email.py
- tests/test_taskhandler_transfer_email.py
Support HTML based email bodies by default with the option to override the content type to text/plain
> Feat: HTML Emails

- .devcontainer/devcontainer.json
- CHANGELOG.md
- README.md
- pyproject.toml
- src/opentaskpy/config/loader.py
- tests/test_config_loader.py
Implements: https://github.com/adammcdonagh/open-task-framework/issues/118
> Feat: Add support for overriding nested variables from environment variables

- .github/workflows/daily_test.yml
- .github/workflows/test.yml
- CHANGELOG.md
- README.md
- pyproject.toml
- src/opentaskpy/config/loader.py
- src/opentaskpy/config/schemas/transfer/email_destination.json
- src/opentaskpy/filters/default_filters.py
- src/opentaskpy/remotehandlers/email.py
- test/cfg/filters/custom_ordinal_date.py
- test/cfg/filters/md5.py
- tests/test_batch_validator.py
- tests/test_config_loader.py
- tests/test_taskhandler_transfer_email.py
Adds support for custom Jinja2 filters, improvements to the email destination handler, and code refactoring to simplify filter management
* Added support for custom filters in Jinja2 templates by loading Python functions from the `<config>/filters` directory. Default filters such as `base64_encode`, `delta_days`, and `utc_now` are moved to their own file. [[1]](diffhunk://#diff-5a5e816c0626a646659c77c11d034888d1a6bb680aebeef8f05ec68a5e91d5f7R19) [[2]](diffhunk://#diff-309275f04e8c6235f468f112a44f52421196a0fe331f0c2cecc42b3eba7e5c41R1-R74) [[3]](diffhunk://#diff-986467a8b0010acca7e3dda0be0cc3c11081e345e8f463de027073c25283a0e4R1-R44) [[4]](diffhunk://#diff-e6a174edc2566a80200ad7bea6f0f385c7b458c8bc373b4892240b6efde0e60aR1-R21)
* Enhanced the email destination handler to allow loading the …
> feat: extensible filters & email improvements

- src/opentaskpy/taskhandlers/transfer.py
This pull request refactors how temporary GnuPG home directories are managed in the `transfer.py` task handler to improve code reuse, consistency, and cleanup. The main changes introduce helper methods for setting up and tidying GnuPG directories, replacing duplicated logic in both encryption and decryption workflows.
**GnuPG staging directory management:**
* Introduced a new `_get_staging_directory` method to consistently generate a unique staging directory, using the `OTF_STAGING_DIR` environment variable if set, or a default base otherwise.
* Added `_setup_gnupg` and `_tidy_gnupg_home` helper methods to handle creation and cleanup of GnuPG home directories, centralizing logic and ensuring proper resource management.
**Encryption and decryption workflow refactoring:**
* Updated …
> feat: Tidy GPG logic and move gpg home to a temp dir
