.vscode/launch.json
CHANGELOG.md
README.md
pyproject.toml
src/opentaskpy/cli/task_run.py
src/opentaskpy/config/loader.py
src/opentaskpy/otflogging.py
src/opentaskpy/remotehandlers/local.py
src/opentaskpy/remotehandlers/sftp.py
src/opentaskpy/remotehandlers/ssh.py
src/opentaskpy/taskhandlers/batch.py
src/opentaskpy/taskhandlers/execution.py
src/opentaskpy/taskhandlers/taskhandler.py
src/opentaskpy/taskhandlers/transfer.py
tests/file_helper.py
tests/test_logging.py
tests/test_taskhandler_batch.py

Closes #21 
- Added JSON formatter for logging to stderr. This replaces the default Python logging format with structured JSON output. This is enabled by setting the `OTF_LOG_JSON` environment variable to `1`. Log files are not impact, as these are always in standard format, as this is required for the batch log parsing to allow for rerunability.
- Tidy up logging
- Fix SSH transfers to ensure that SSH connections are fully closed after use
- Update SFTP transfers to use .partial file extension while files are being uploaded, and then rename them to their final name the transfer is complete.
- Altered log level for some messages
- Added `OTF_BATCH_RESUME_LOG_DATE` to allow resuming of batch runs from a specific date. This is useful if you want to rerun a batch from a specific date, …

Logging and minor SFTP/SSH transfer changes

---

CHANGELOG.md
pyproject.toml
src/opentaskpy/cli/task_run.py
src/opentaskpy/config/schemas/transfer/local_destination.json
src/opentaskpy/config/schemas/transfer/local_destination/protocol.json
src/opentaskpy/config/schemas/transfer/local_source.json
src/opentaskpy/config/schemas/transfer/local_source/postCopyAction.json
src/opentaskpy/config/schemas/transfer/local_source/protocol.json
src/opentaskpy/config/schemas/transfer/sftp_destination/protocol.json
src/opentaskpy/config/schemas/transfer/sftp_source/protocol.json
tests/test_schema_validate.py

Transfers that weren't using SSH prootcol couldn't be used due to bad schemas. Updated these so other protocols can actually be used.

Fix issue with schema definitions

---

.vscode/launch.json
CHANGELOG.md
README.md
pyproject.toml
src/opentaskpy/cli/task_run.py
src/opentaskpy/config/loader.py
test/cfg/transfers/scp-basic-ssh-vars.json.j2
test/cfg/variables.json.j2
tests/test_config_loader.py

- Add mode override docs to `--help`
- Allow task definitions to use a whole templated object within them. e.g a protocol definition could be defined as a global variable to define SFTP connectivity to a commonly used source/destination. This is done using `.j2` task definition file instead of `.json`

Allow jinja2 template task definitions

---

.pre-commit-config.yaml
CHANGELOG.md
pyproject.toml
src/opentaskpy/cli/task_run.py
src/opentaskpy/remotehandlers/ssh.py
src/opentaskpy/taskhandlers/batch.py
tests/test_config_loader.py

If theres 2 tasks in a batch that rely on the same external addon, if they try and load too quickly you get partially loaded package errors.
Added a sleep between tasks in a batch so they don't start up so quickly and the package has time to load into memory.

Importing modules in batch tasks fail when there's more than 2 tasks

---

CHANGELOG.md
src/opentaskpy/taskhandlers/batch.py
src/opentaskpy/taskhandlers/transfer.py

Fixes #52 
Ensure that exceptions get output properly
Also ensure exceptions thrown by a batchtask are caught by the batch itself and the result_result is always called against the task handler to ensure that the log gets renamed

Allways call return_result for exceptions thrown by batch task

---

CHANGELOG.md
src/opentaskpy/remotehandlers/local.py
src/opentaskpy/taskhandlers/transfer.py
test/cfg/transfers/local-basic.json
tests/test_task_run.py

There's no reason to use the staging directory for local files. If the source procotol is local, then the step will be skipped, and also the step that removes the staging directory will be skipped.
Fixes #39.

Prevent local files being moved to staging directory

---

CHANGELOG.md
README.md
pyproject.toml
src/opentaskpy/config/loader.py
src/opentaskpy/remotehandlers/remotehandler.py
tests/test_config_loader.py

This pull request replaces the existing `now` Jinja function with `utc_now` in order to always return the UTC time. The `now` function will now return the localtime of the machine running the task instead.

Replace `now` Jinja function with `utc_now`

---

CHANGELOG.md
pyproject.toml
src/opentaskpy/config/schemas/transfer/sftp_destination/protocol.json
src/opentaskpy/remotehandlers/sftp.py
src/opentaskpy/taskhandlers/transfer.py
tests/test_task_run.py
tests/test_taskhandler_transfer_local.py
tests/test_taskhandler_transfer_sftp.py

This pull request updates the SFTP transfer to add a new protocol option called "supportsStatAfterUpload" which allows the user to prevent the "stat" command from being run after upload. 
Additionally, it fixes a minor issue where the destination path would start with "//" when uploading to the root directory.

New `supportsStatAfterUpload` SFTP protocol option

---

CHANGELOG.md
pyproject.toml
src/opentaskpy/config/schemas/transfer/encryption.json
src/opentaskpy/taskhandlers/transfer.py
tests/test_schema_validate.py
tests/test_taskhandler_transfer_local.py

This pull request adds the option to sign encrypted files using a private key. It introduces a new property called "sign" in the encryption configuration, which can be set to true to enable signing. Additionally, a "private_key" property is required when signing is enabled. This feature enhances the security of encrypted files by providing a way to verify their authenticity.

Add option to sign encrypted files using a private key

---

.devcontainer/devcontainer.json
CHANGELOG.md
pyproject.toml
src/opentaskpy/config/schemas/transfer/encryption.json
src/opentaskpy/taskhandlers/transfer.py
tests/test_docker_task_run.py
tests/test_taskhandler_transfer_local.py

Previously, the file extension for encrypted files was hardcoded as `.gpg`. This pull request introduces a new configuration option called `output_extension` that allows users to choose a different file extension for encrypted files. This is particularly useful for companies that use `.pgp` instead of `.gpg`.
Fixes #82

Allow choice of file extension for encryption

---

.github/workflows/test.yml
CHANGELOG.md
src/opentaskpy/taskhandlers/transfer.py
tests/test_taskhandler_transfer_sftp.py

Looked like files were not getting renamed from the original report, but turned out to be a misconfiguration. However on looking deeper in some instances the unencrypted of the file was somehow getting uploaded too. 
Ensure that the corrent file list gets passed to the SFTP handler when doing encryption.
Fixes #79.

Fixes unencrypted files being transferred

---

.devcontainer/devcontainer.json
CHANGELOG.md
README.md
codecov.yml
pyproject.toml
src/opentaskpy/config/schemas.py
src/opentaskpy/config/schemas/cacheable_variables.json
src/opentaskpy/config/schemas/transfer/dummy_source.json
src/opentaskpy/config/schemas/transfer/dummy_source/protocol.json
src/opentaskpy/config/variablecaching/cache_utils.py
src/opentaskpy/config/variablecaching/file.py
src/opentaskpy/exceptions.py
src/opentaskpy/remotehandlers/dummy.py
src/opentaskpy/remotehandlers/remotehandler.py
src/opentaskpy/taskhandlers/transfer.py
tests/test_cacheable_variable_file.py
tests/test_dummy_transfer_schema_validate.py
tests/test_remotehandler.py
tests/test_taskhandler_transfer_dummy.py

This pull request adds support for cacheable variables. It includes the following changes:
- Added new cacheable variables
- Updated dependencies to include "omegaconf >= 2.3.0"
- Added a new JSON schema for a dummy source protocol
- Added a new exception class for caching plugin errors
- Updated VS Code settings to include write permissions for specific repositories in Codespaces
- Added new test cases for cacheable variables and caching plugins
- Added utility functions for updating the cache with new values
- Added a new JSON schema for cacheable variables
- Added new test cases for validating transfer JSON with dummy source and cacheable variables
These changes enable the caching of specific variables and provide flexibility for using different caching plugins.

Add cacheable variables support

---

.github/dependabot.yml
.github/workflows/daily_test.yml
.github/workflows/test.yml
CHANGELOG.md
pyproject.toml
src/opentaskpy/otflogging.py
tests/conftest.py
tests/test_logging.py

* Basic dependabot config
* Fix pytests that rely on docker compose that still used v1 docker-compose syntax which now break GitHub test workflow caused by - https://github.com/actions/runner-images/issues/9692

Add dependabot config

---

CHANGELOG.md
pyproject.toml
src/opentaskpy/config/loader.py

Prevent new lazy loading logic to load in unresolved variables from conflicting with the no op functionality where some variables are intentionally not resolved.

fix: Lazy loading breaks `noop`

---

.vscode/launch.json
CHANGELOG.md
pyproject.toml
src/opentaskpy/config/loader.py
tests/test_config_loader.py

When loading nested variables Jinja2 errored with:
`TypeError: Can't compile non template nodes`
Now, all variables will be converted to a string, if not already a string, before being passed for evaluation

fix: Lazy loading fails when evaluating nested vars

---

CHANGELOG.md
src/opentaskpy/taskhandlers/transfer.py

This pull request includes a bug fix and a minor code adjustment in the `src/opentaskpy/taskhandlers/transfer.py` file. The most important changes are listed below:
Bug Fix:
* `src/opentaskpy/taskhandlers/transfer.py`: Moved the increment of the variable `i` to ensure it is executed in the appropriate control flow, preventing potential issues in the loop logic.
Fixes #102

Moved counter for checking handler classes to outside the condition

---

CHANGELOG.md
src/opentaskpy/taskhandlers/transfer.py

Fixes #106 
* Validate that any directories being deleted actually exist
* Update exception logging for transfers to print before connections are closed and tidy up is run.

106 unexplained errors deleting gpg keystore after decryption

---

CHANGELOG.md
pyproject.toml
src/opentaskpy/config/schemas/transfer/sftp_destination/protocol.json
src/opentaskpy/config/schemas/transfer/sftp_source/protocol.json
src/opentaskpy/remotehandlers/sftp.py
tests/test_taskhandler_transfer_sftp.py

* Added `timeout` property to the SFTP protocol schema in `protocol.json` files for both SFTP source and destination. [[1]](diffhunk://#diff-bddd03045bdb25ac06732e916690af663f921c46b69cad95168ee64163380983R19-R21) [[2]](diffhunk://#diff-068f423f8daf1ac57df1ec17144dcafb43d97f2a7c57e679931f76094e83d27aR19-R21)
* Updated the `connect` method in `sftp.py` to use the configurable `timeout` value from the protocol definition, defaulting to 3 seconds if not specified.
* Modified the SFTP transfer test cases to include the `timeout` property in the protocol definition.

Feat: Configure SFTP timeout

---

CHANGELOG.md
pyproject.toml
src/opentaskpy/remotehandlers/sftp.py
tests/test_taskhandler_transfer_sftp.py

Added auto-dir creation for PCA
- Checking File Existence
- Checking existing directory existence
- Added related test

PostCopy Action Improvements

---

.github/workflows/daily_test.yml
.github/workflows/test.yml
.vscode/launch.json
CHANGELOG.md
pyproject.toml
src/opentaskpy/taskhandlers/batch.py
test/cfg/batch/batch-dependencies-complex-fail.json
test/cfg/batch/batch-dependencies-complex.json
test/cfg/batch/test-batch.json
test/cfg/executions/exit-1-local.json
test/cfg/executions/sleep-5-local.json
test/cfg/executions/sleep-7-local.json
test/cfg/transfers/filewatch-5-error-sftp.json
tests/test_taskhandler_batch.py

In some cases, batches go stale.
Looks like it is due to:
- Failed dependencies
- Timed out dependencies (when batch times out before task)
This PR tries to fix it

Fix: Stale batches on dependency failures

---

.vscode/launch.json
CHANGELOG.md
pyproject.toml
src/opentaskpy/taskhandlers/batch.py
test/cfg/batch/batch-parallel-dependencies.json
tests/test_taskhandler_batch.py

This PR resolves batch tasks being skipped despite all dependencies completing.
The cause was a delay between checking for running tasks and the Execution task not being in Running state yet.

Fix: Batch Task executions being skipped

---

.pre-commit-config.yaml
CHANGELOG.md
pyproject.toml
src/opentaskpy/config/schemas/transfer/dummy_source.json
src/opentaskpy/config/schemas/transfer/email_destination.json
src/opentaskpy/taskhandlers/transfer.py
tests/test_taskhandler_transfer_dummy.py
tests/test_taskhandler_transfer_email.py

This pull request introduces several updates and fixes across the codebase, including changes to configuration files, schema definitions, task handler logic, and test cases. The most significant changes involve adjustments to the email destination and dummy source task handlers, as well as improvements to testing coverage. Below is a breakdown of the key changes:
* Updated the `mypy` pre-commit hook in `.pre-commit-config.yaml` to use `python` as the entry and `system` as the language, and modified the `args` to invoke `mypy` as a module.
* Added a new `message` attribute to the email destination schema in `email_destination.json` to support custom email body content.
* Removed the `accessToken` requirement from the dummy source schema in `dummy_source.json`, simplifying its usage.
* …

fix: Email body

---

CHANGELOG.md
pyproject.toml
src/opentaskpy/remotehandlers/email.py

1.  Email content file read once before iterating over recipients. Avoids reading the file multiple times. 
2. Delete content file only if all emails succeed. The delete operation now runs after all recipients have been processed. If any send fails, deletion is skipped.

Minor adjustments to email file content
